spring:
  application:
    name: admin-api
  cloud:
    config:
      uri: http://localhost:8888/
      profile: dev
      label: master
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8080
  context-path: /api/j

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

logging:
  file: ${spring.application.name}.log

